### ISSUE TITLE
Plain text search error

### ISSUE THREAD

**Issue by NetBUG** [interrogator/corpkit#11]
When trying to make plain text search I get error in the console

```
18:39:45: Interrogating corpus ...
Traceback (most recent call last):
  File "corpkit/corpkit-gui.py", line 520, in runner
    command()
  File "corpkit/corpkit-gui.py", line 1270, in do_interrogation
    interrodata = interrogator(corpus_fullpath.get(), selected_option, **interrogator_args)
  File "/Users/ourzhumt/projects/corpkit/corpkit/interrogator.py", line 1627, in interrogator
    result_from_file = plaintext_simple_search(query, data)
  File "/Users/ourzhumt/projects/corpkit/corpkit/interrogator.py", line 740, in plaintext_simple_search
    for m in range(matches):
TypeError: range() integer end argument expected, got list.
```

**Comment by interrogator** [comment]
Looks like it should be `for m in range(len(matches))`. Will test.

**Comment by interrogator** [comment]
9f4fa5f should fix this error, alongside a few others that were happening during plaintext search.
