### ISSUE TITLE
TypeError: 'bool' object is not iterable   on Linux

### ISSUE THREAD

**Issue by aliabbasjp** [interrogator/corpkit#40]
I get following error on Ubuntu 14 machine

```

corpkit@cowtest:no-corpus> add ../  
concordance  search       testing        
corpkit@cowtest:no-corpus> add ../../  
concordance  search       testing        
corpkit@cowtest:no-corpus> add ../fulltxt/anonymized  
../fulltxt/anonymized added to /corpus/cowtest/data/anonymized.  
corpkit@cowtest:no-corpus> set anonymized as corpus  
Corpus: /corpus/cowtest/data/anonymized  
corpkit@cowtest:anonymized> parse corpus  
Making list of files ...   
Traceback (most recent call last):  
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 2168, in interpreter  
    out = run_command(tokens)  
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 1113, in run_command  
    out = command(tokens[1:])  
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 1437, in parse_corpus  
    parsed = to_parse.parse(**kwargs)  
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/corpus.py", line 930, in parse  
    **kwargs  
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/make.py", line 228, in make_corpus  
    out_ext=kwargs.get('output_format'))  
TypeError: 'bool' object is not iterable  
corpkit@cowtest:anonymized> 
```

**Comment by interrogator** [comment]
Thanks for the report. I will be able to take a look later today. Do the files in your corpus all have a `.txt` extension?

**Comment by aliabbasjp** [comment]
NO

**Comment by interrogator** [comment]
Alright. Try making sure they are plain text, with a .txt extension, and go for it again. Your corpus can be either a folder of files, or a folder containing subfolders which contain files.

**Comment by aliabbasjp** [comment]
Now I get following error: on command : parse corpus

```

ParserAnnotator: 173.3 sec.
NERCombinerAnnotator: 14.6 sec.
DeterministicCorefAnnotator: 8.2 sec.  
TOTAL: 197.9 sec. for 45060 tokens at 227.7 tokens/sec.
Pipeline setup: 6.7 sec.
Total time for StanfordCoreNLP pipeline: 211.0 sec.
14:34:22: Parsing finished. Moving parsed files into place ...
Traceback (most recent call last):
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 2168, in interpreter
    out = run_command(tokens)
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 1113, in run_command
    out = command(tokens[1:])
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/env.py", line 1437, in parse_corpus
    parsed = to_parse.parse(**kwargs) 
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/corpus.py", line 930, in parse
    **kwargs
  File "/home/domas/anaconda2/lib/python2.7/site-packages/corpkit/make.py", line 388, in make_corpus
    rename_all_files(outpath)
UnboundLocalError: local variable 'outpath' referenced before assignment
```

**Comment by interrogator** [comment]
Oh, my mistake. OK, it's fixed in the master branch on GitHub now, so update your copy and try again. Can you confirm that the parse method works for you now?

**Comment by interrogator** [comment]
Closing; see #41  for the `UnboundLocalError`
